Update xrdp
rhel compatible

diff --git a/instfiles/init.d/xrdp b/instfiles/init.d/xrdp
--- a/instfiles/init.d/xrdp
+++ b/instfiles/init.d/xrdp
@@ -1,4 +1,4 @@
-#!/bin/sh -e
+#!/bin/sh
 #
 # start/stop xrdp and sesman daemons
 #
@@ -29,218 +29,29 @@ DESC="Remote Desktop Protocol server"
 
 test -x $DAEMON || exit 0
 
+TDEB=no
 if [ -e /etc/debian_version ]; then
     . /lib/lsb/init-functions
+    TDEB=yes
 elif [ -e /etc/init.d/functions ] ; then
     . /etc/init.d/functions
+    TDEB=no
 fi
-
-#
-# START LSB FILLER - http://tech.mnnguyen.com/?p=37
-#
-if ! type log_daemon_msg 2>&1 |grep -qai function ; then
-# no lsb setup?  no problem.  we will add them in
-
-log_use_fancy_output () {
-    TPUT=/usr/bin/tput
-    EXPR=/usr/bin/expr
-    if [ -t 1 ] && [ "x$TERM" != "" ] && [ "x$TERM" != "xdumb" ] && [ -x $TPUT ] && [ -x $EXPR ] && $TPUT hpa 60 >/dev/null 2>&1 && $TPUT setaf 1 >/dev/null 2>&1; then
-        [ -z $FANCYTTY ] && FANCYTTY=1 || true
-    else
-        FANCYTTY=0
-    fi
-    case "$FANCYTTY" in
-        1|Y|yes|true)   true;;
-        *)              false;;
-    esac
-}
-
-log_success_msg () {
-    if [ -n "${1:-}" ]; then
-        log_begin_msg $@
-    fi
-    log_end_msg 0
-}
-
-log_failure_msg () {
-    if [ -n "${1:-}" ]; then
-        log_begin_msg $@
-    fi
-    log_end_msg 1 || true
-}
-
-log_warning_msg () {
-    if [ -n "${1:-}" ]; then
-        log_begin_msg $@
-    fi
-    log_end_msg 255 || true
-}
-
-#
-# NON-LSB HELPER FUNCTIONS
-#
-# int get_lsb_header_val (char *scriptpathname, char *key)
-get_lsb_header_val () {
-        if [ ! -f "$1" ] || [ -z "${2:-}" ]; then
-                return 1
-        fi
-        LSB_S="### BEGIN INIT INFO"
-        LSB_E="### END INIT INFO"
-        sed -n "/$LSB_S/,/$LSB_E/ s/# $2: \(.*\)/\1/p" $1
-}
-
-# int log_begin_message (char *message)
-log_begin_msg () {
-    if [ -z "${1:-}" ]; then
-        return 1
-    fi
-    echo -n "$@"
-}
-
-# Sample usage:
-# log_daemon_msg "Starting GNOME Login Manager" "gdm"
-#
-# On Debian, would output "Starting GNOME Login Manager: gdm"
-# On Ubuntu, would output " * Starting GNOME Login Manager..."
-#
-# If the second argument is omitted, logging suitable for use with
-# log_progress_msg() is used:
-#
-# log_daemon_msg "Starting remote filesystem services"
-#
-# On Debian, would output "Starting remote filesystem services:"
-# On Ubuntu, would output " * Starting remote filesystem services..."
-
-log_daemon_msg () {
-    if [ -z "${1:-}" ]; then
-        return 1
-    fi
-    log_daemon_msg_pre "$@"
-
-    if [ -z "${2:-}" ]; then
-        echo -n "$1:"
-        return
-    fi
-
-    echo -n "$1: $2"
-    log_daemon_msg_post "$@"
-}
-
-# #319739
-#
-# Per policy docs:
-#
-#     log_daemon_msg "Starting remote file system services"
-#     log_progress_msg "nfsd"; start-stop-daemon --start --quiet nfsd
-#     log_progress_msg "mountd"; start-stop-daemon --start --quiet mountd
-#     log_progress_msg "ugidd"; start-stop-daemon --start --quiet ugidd
-#     log_end_msg 0
-#
-# You could also do something fancy with log_end_msg here based on the
-# return values of start-stop-daemon; this is left as an exercise for
-# the reader...
-#
-# On Ubuntu, one would expect log_progress_msg to be a no-op.
-log_progress_msg () {
-    if [ -z "${1:-}" ]; then
-        return 1
-    fi
-    echo -n " $@"
-}
-
-# int log_end_message (int exitstatus)
-log_end_msg () {
-    # If no arguments were passed, return
-    if [ -z "${1:-}" ]; then
-        return 1
-    fi
-
-    retval=$1
-
-    log_end_msg_pre "$@"
-
-    # Only do the fancy stuff if we have an appropriate terminal
-    # and if /usr is already mounted
-    if log_use_fancy_output; then
-        RED=`$TPUT setaf 1`
-        YELLOW=`$TPUT setaf 3`
-        NORMAL=`$TPUT op`
-    else
-        RED=''
-        YELLOW=''
-        NORMAL=''
-    fi
-
-    if [ $1 -eq 0 ]; then
-        echo "."
-    elif [ $1 -eq 255 ]; then
-        /bin/echo -e " ${YELLOW}(warning).${NORMAL}"
-    else
-        /bin/echo -e " ${RED}failed!${NORMAL}"
-    fi
-    log_end_msg_post "$@"
-    return $retval
-}
-
-log_action_msg () {
-    echo "$@."
-}
-
-log_action_begin_msg () {
-    echo -n "$@..."
-}
-
-log_action_cont_msg () {
-    echo -n "$@..."
-}
-
-log_action_end_msg () {
-    log_action_end_msg_pre "$@"
-    if [ -z "${2:-}" ]; then
-        end="."
-    else
-        end=" ($2)."
-    fi
-
-    if [ $1 -eq 0 ]; then
-        echo "done${end}"
-    else
-        if log_use_fancy_output; then
-            RED=`$TPUT setaf 1`
-            NORMAL=`$TPUT op`
-            /bin/echo -e "${RED}failed${end}${NORMAL}"
-        else
-            echo "failed${end}"
-        fi
-    fi
-    log_action_end_msg_post "$@"
-}
-
-# Hooks for /etc/lsb-base-logging.sh
-log_daemon_msg_pre () { :; }
-log_daemon_msg_post () { :; }
-log_end_msg_pre () { :; }
-log_end_msg_post () { :; }
-log_action_end_msg_pre () { :; }
-log_action_end_msg_post () { :; }
-
-fi
-
-#
-# END LSB FILLER
-#
 
 check_root()  {
     if [ "$(id -u)" != "0" ]; then
-        log_failure_msg "You must be root to start, stop or restart $NAME."
+    	if [ "$TDEB" = "yes" ] ; then
+        	log_failure_msg "You must be root to start, stop or restart $NAME."
+        else
+        	echo "You must be root to start, stop or restart $NAME."
+        fi
         exit 4
     fi
 }
 
 force_stop() {
-
-DELAY=1
-PROCLIST="xrdp-sesman xrdp-sessvc xrdp-chansrv X11rdp Xvnc"
+    DELAY=1
+    PROCLIST="xrdp-sesman xrdp-sessvc xrdp-chansrv X11rdp Xvnc"
 
     for p in $PROCLIST; do
       pgrep -x $p >/dev/null && pkill  -x $p
@@ -252,7 +63,11 @@ PROCLIST="xrdp-sesman xrdp-sessvc xrdp-chansrv X11rdp Xvnc"
     sleep $DELAY
     pgrep -fx $DAEMON  >/dev/null && pkill -9 -fx $DAEMON
 
-   rm -f $PIDDIR/xrdp*.pid
+    if [ "$TDEB" = "yes" ] ; then
+        rm -f $PIDDIR/xrdp*.pid
+    else
+    	rm -f /var/run/xrdp*.pid
+    fi
 }
 
 if [ -r /etc/default/$NAME ]; then
@@ -262,21 +77,35 @@ fi
 # Tasks that can only be run as root
 if [ "$(id -u)" = "0" ]; then
     # Check for pid dir
-    if [ ! -d $PIDDIR ] ; then
-        mkdir $PIDDIR
+    if [ "$TDEB" = "yes" ] ; then
+        if [ ! -d $PIDDIR ] ; then
+                mkdir $PIDDIR
+                chown $USERID:$USERID $PIDDIR
+        fi
     fi
-    chown $USERID:$USERID $PIDDIR
-
+    
     # Check for rsa key 
     if [ ! -f $RSAKEYS ] ; then
-        log_action_begin_msg "Generating xrdp RSA keys..."
+    	if [ "$TDEB" = "yes" ] ; then
+        	log_action_begin_msg "Generating xrdp RSA keys..."
+        else
+        	echo "Generating xrdp RSA keys..."
+        fi        
         (umask 077 ; xrdp-keygen xrdp $RSAKEYS)
         chown $USERID:$USERID $RSAKEYS
         if [ ! -f $RSAKEYS ] ; then
-            log_action_end_msg 1 "could not create $RSAKEYS"
-            exit 1
+	    	if [ "$TDEB" = "yes" ] ; then
+	        	log_action_end_msg 1 "could not create $RSAKEYS"
+	        else
+	        	echo "could not create $RSAKEYS"
+	        fi            
+            	exit 1
         fi
-        log_action_end_msg 0 "done"
+    	if [ "$TDEB" = "yes" ] ; then
+        	log_action_end_msg 0 "done"
+        else
+        	echo "done"
+        fi        
     fi
 fi
 
@@ -285,29 +114,39 @@ case "$1" in
   start)
         check_root
         exitval=0
-        log_daemon_msg "Starting $DESC " 
-        if pidofproc -p $PIDDIR/$NAME.pid $DAEMON > /dev/null; then
-            log_progress_msg "$NAME apparently already running"
-            log_end_msg 0
-            exit 0
+        if [ "$TDEB" = "yes" ]; then
+        	log_daemon_msg "Starting $DESC "
+	        if pidofproc -p $PIDDIR/$NAME.pid $DAEMON > /dev/null; then
+	            log_progress_msg "$NAME apparently already running"
+	            log_end_msg 0
+	            exit 0
+	        fi
+	        log_progress_msg $NAME
+	        start-stop-daemon --start --quiet --oknodo  --pidfile $PIDDIR/$NAME.pid \
+		    --chuid $USERID:$USERID --exec $DAEMON >/dev/null
+	        exitval=$?
+		if [ "$SESMAN_START" = "yes" ] ; then
+	            log_progress_msg "sesman"
+	            start-stop-daemon --start --quiet --oknodo --pidfile $PIDDIR/xrdp-sesman.pid \
+		       --exec $SDAEMON >/dev/null
+	            value=$?
+	            [ $value -gt 0 ] && exitval=$value
+	        fi
+	        # Make pidfile readables for all users (for status to work)
+	        [ -e $PIDDIR/xrdp-sesman.pid ] && chmod 0644 $PIDDIR/xrdp-sesman.pid
+	        [ -e $PIDDIR/$NAME.pid ] && chmod 0644 $PIDDIR/$NAME.pid
+	        # Note: Unfortunately, xrdp currently takes too long to create
+	        # the pidffile unless properly patched
+	        log_end_msg $exitval
         fi
-        log_progress_msg $NAME
-        start-stop-daemon --start --quiet --oknodo  --pidfile $PIDDIR/$NAME.pid \
-	    --chuid $USERID:$USERID --exec $DAEMON >/dev/null
-        exitval=$?
-	if [ "$SESMAN_START" = "yes" ] ; then
-            log_progress_msg "sesman"
-            start-stop-daemon --start --quiet --oknodo --pidfile $PIDDIR/xrdp-sesman.pid \
-	       --exec $SDAEMON >/dev/null
-            value=$?
-            [ $value -gt 0 ] && exitval=$value
+        if [ "$TDEB" = "no" ]; then
+        	echo "Starting..."
+        	daemon --pidfile /var/run/$NAME.pid $DAEMON
+        	daemon --pidfile /var/run/xrdp-sesman.pid $SDAEMON
+	        [ -e /var/run/xrdp-sesman.pid ] && chmod 0644 /var/run/xrdp-sesman.pid
+	        [ -e /var/run/$NAME.pid ] && chmod 0644 /var/run/$NAME.pid   
+	        exit 0
         fi
-        # Make pidfile readables for all users (for status to work)
-        [ -e $PIDDIR/xrdp-sesman.pid ] && chmod 0644 $PIDDIR/xrdp-sesman.pid
-        [ -e $PIDDIR/$NAME.pid ] && chmod 0644 $PIDDIR/$NAME.pid
-        # Note: Unfortunately, xrdp currently takes too long to create
-        # the pidffile unless properly patched
-        log_end_msg $exitval
 	;;
   stop)
         check_root
@@ -316,25 +155,44 @@ case "$1" in
 	    exit 0
 	}
         exitval=0
-        log_daemon_msg "Stopping RDP Session manager " 
-        log_progress_msg "sesman"
-        if pidofproc -p  $PIDDIR/xrdp-sesman.pid $SDAEMON  > /dev/null; then
-            start-stop-daemon --stop --quiet --oknodo --pidfile $PIDDIR/xrdp-sesman.pid \
-                --chuid $USERID:$USERID --exec $SDAEMON
-            exitval=$?
-        else
-            log_progress_msg "apparently not running"
+        if [ "$TDEB" = "yes" ]; then
+        	log_daemon_msg "Stopping RDP Session manager "
+	        log_progress_msg "sesman"
+	        if pidofproc -p  $PIDDIR/xrdp-sesman.pid $SDAEMON  > /dev/null; then
+	            start-stop-daemon --stop --quiet --oknodo --pidfile $PIDDIR/xrdp-sesman.pid \
+	                --chuid $USERID:$USERID --exec $SDAEMON
+	            exitval=$?
+	        else
+	            log_progress_msg "apparently not running"
+	        fi
+	        log_progress_msg $NAME
+	        if pidofproc -p  $PIDDIR/$NAME.pid $DAEMON  > /dev/null; then
+	            start-stop-daemon --stop --quiet --oknodo --pidfile $PIDDIR/$NAME.pid \
+		    --exec $DAEMON
+	            value=$?
+	            [ $value -gt 0 ] && exitval=$value
+	        else
+	            log_progress_msg "apparently not running"
+	        fi
+	        log_end_msg $exitval
         fi
-        log_progress_msg $NAME
-        if pidofproc -p  $PIDDIR/$NAME.pid $DAEMON  > /dev/null; then
-            start-stop-daemon --stop --quiet --oknodo --pidfile $PIDDIR/$NAME.pid \
-	    --exec $DAEMON
-            value=$?
-            [ $value -gt 0 ] && exitval=$value
-        else
-            log_progress_msg "apparently not running"
+        if [ "$TDEB" = "no" ]; then
+        	echo 'Killing sesman'
+        	if [ -f /var/run/$NAME.pid ]; then
+        		kill -TERM $(cat /var/run/$NAME.pid)
+		else
+        		echo "No PID file at /var/run/$NAME.pid"
+        	fi
+        	echo 'DONE!'
+        	echo "Killing $NAME"
+        	if [ -f /var/run/xrdp-sesman.pid ]; then
+        		kill -TERM $(cat /var/run/xrdp-sesman.pid)
+		else
+        		echo "No PID file at /var/run/xrdp-sesman.pid"        		
+        	fi
+        	echo 'DONE!'
+        	exit 0
         fi
-        log_end_msg $exitval
 	;;
   force-stop)
 	$0 stop
@@ -349,31 +207,64 @@ case "$1" in
 	$0 start
 	;;
   reload)
-        log_warning_msg "Reloading $NAME daemon: not implemented, as the daemon"
-        log_warning_msg "cannot re-read the config file (use restart)."
+    	if [ "$TDEB" = "yes" ] ; then
+        	log_warning_msg "Reloading $NAME daemon: not implemented, as the daemon"
+        	log_warning_msg "cannot re-read the config file (use restart)."
+        else
+        	echo "Reloading $NAME daemon: not implemented, as the daemon"
+        	echo "cannot re-read the config file (use restart)."
+        fi         
         ;;
   status)
         exitval=0
-        log_daemon_msg "Checking status of $DESC" "$NAME"
-        if pidofproc -p  $PIDDIR/$NAME.pid $DAEMON  > /dev/null; then
-            log_progress_msg "running"
-            log_end_msg 0
-        else
-            log_progress_msg "apparently not running"
-            log_end_msg 1 || true
-            exitval=1
-        fi
-	if [ "$SESMAN_START" = "yes" ] ; then
-            log_daemon_msg "Checking status of RDP Session Manager" "sesman"
-            if pidofproc -p  $PIDDIR/xrdp-sesman.pid $SDAEMON  > /dev/null; then
-                log_progress_msg "running"
-                log_end_msg 0
-            else
-                log_progress_msg "apparently not running"
-                log_end_msg 1 || true
-                exitval=1
-            fi
+        if [ "$TDEB" = "yes" ]; then
+        	log_daemon_msg "Checking status of $DESC" "$NAME"
+	        if pidofproc -p $PIDDIR/$NAME.pid $DAEMON  > /dev/null; then
+	            log_progress_msg "running"
+	            log_end_msg 0
+	        else
+	            log_progress_msg "apparently not running"
+	            log_end_msg 1 || true
+	            exitval=1
+	        fi
+		if [ "$SESMAN_START" = "yes" ] ; then
+	            log_daemon_msg "Checking status of RDP Session Manager" "sesman"
+	            if pidofproc -p  $PIDDIR/xrdp-sesman.pid $SDAEMON  > /dev/null; then
+	                log_progress_msg "running"
+	                log_end_msg 0
+	            else
+	                log_progress_msg "apparently not running"
+	                log_end_msg 1 || true
+	                exitval=1
+	            fi
+		fi
 	fi
+	
+	if [ "$TDEB" = "no" ]; then
+		echo "Checking $NAME..."
+	        if [ -f /var/run/$NAME.pid ]; then
+	            PID=`cat /var/run/$NAME.pid`
+	            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
+	                echo "$NAME Process dead but pidfile exists"
+	            else
+	                echo "$NAME Running"
+	            fi
+	        else
+	            echo "$NAME Service not running"
+	        fi
+	        
+		echo "Checking sesman..."
+	        if [ -f /var/run/xrdp-sesman.pid ]; then
+	            PID=`cat /var/run/xrdp-sesman.pid`
+	            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
+	                echo "sesman Process dead but pidfile exists"
+	            else
+	                echo "sesman Running"
+	            fi
+	        else
+	            echo "sesman Service not running"
+	        fi	        
+        fi
         exit $exitval
         ;;
   *)
